apiVersion: v1
kind: ConfigMap
metadata:
  name: claims-integrity-config
  namespace: claims-integrity
  labels:
    app.kubernetes.io/name: claims-integrity
    app.kubernetes.io/part-of: claims-payment-integrity-poc
data:
  ENVIRONMENT: dev
  KAFKA_TOPIC: claim-events
  KAFKA_CONSUMER_GROUP: claims-rules-engine
  RDS_PORT: "5432"
  RDS_DB_NAME: claims_integrity
