apiVersion: v1
kind: Namespace
metadata:
  name: claims-integrity
  labels:
    app.kubernetes.io/name: claims-integrity
    app.kubernetes.io/part-of: claims-payment-integrity-poc
    environment: dev
