apiVersion: v1
kind: Secret
metadata:
  name: claims-integrity-secrets
  namespace: claims-integrity
  labels:
    app.kubernetes.io/name: claims-integrity
    app.kubernetes.io/part-of: claims-payment-integrity-poc
  annotations:
    public-repo-safety: "example-only-do-not-use-real-secrets"
type: Opaque
stringData:
  MSK_BOOTSTRAP_SERVERS: "replace-with-terraform-output-msk_bootstrap_brokers"
  RDS_HOST: "replace-with-terraform-output-rds_address"
  RDS_USER: "claims_app"
  RDS_PASSWORD: "replace-with-secrets-manager-rds-password"
