apiVersion: v1
kind: Secret
metadata:
  name: claims-integrity-secrets
  namespace: claims-integrity
type: Opaque
stringData:
  MSK_BOOTSTRAP_SERVERS: "replace-with-msk-bootstrap-servers"
  RDS_HOST: "replace-with-rds-host"
  RDS_USER: "replace-with-db-user"
  RDS_PASSWORD: "replace-with-db-password"
